### ISSUE TITLE
Latest version of pnpm not being published on chocolatey

### ISSUE THREAD

**Issue by l-lafin** [MKMZ/ChocolateyPackages#2]
The last version of `pnpm` published on Chocolatey was `8.15.6` and looking at the `Chocolatey package update` there is a silent error happening and preventing new versions from being published.

```
   [1/1] pnpm ERROR: 
     Chocolatey v2.2.2 File specified is either not found or not a .nupkg file. 'pnpm.9.0.6.nupkg ' (7.06s)
```

https://github.com/MKMZ/ChocolateyPackages/actions/runs/8841590400/job/24278923692#step:4:186

**Comment by MKMZ** [comment]
Seems like they changed approach of publishing packages on GitHub. I will look into that.

**Comment by MKMZ** [comment]
New versions are now automatically published by pipeline.
